// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgUzrnQUnbQaYcI8Di8CGx8CxQXI9WPMo',
    appId: '1:44159273910:web:6fcc24ed954e4a31534f17',
    messagingSenderId: '44159273910',
    projectId: 'pegasus-e40ad',
    authDomain: 'pegasus-e40ad.firebaseapp.com',
    storageBucket: 'pegasus-e40ad.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApcV3BsmJpAwdZrFu4pHIlERsOyalvoCg',
    appId: '1:44159273910:android:5017d1645c83ca07534f17',
    messagingSenderId: '44159273910',
    projectId: 'pegasus-e40ad',
    storageBucket: 'pegasus-e40ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8Ca86wneJDmGw5bgVxE9ztplH5AyFDl8',
    appId: '1:44159273910:ios:3b76ca2ef97e96d9534f17',
    messagingSenderId: '44159273910',
    projectId: 'pegasus-e40ad',
    storageBucket: 'pegasus-e40ad.firebasestorage.app',
    iosBundleId: 'com.pegasus.coach',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8Ca86wneJDmGw5bgVxE9ztplH5AyFDl8',
    appId: '1:44159273910:ios:3b76ca2ef97e96d9534f17',
    messagingSenderId: '44159273910',
    projectId: 'pegasus-e40ad',
    storageBucket: 'pegasus-e40ad.firebasestorage.app',
    iosBundleId: 'com.pegasus.coach',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgUzrnQUnbQaYcI8Di8CGx8CxQXI9WPMo',
    appId: '1:44159273910:web:ce45408d0a1c86e6534f17',
    messagingSenderId: '44159273910',
    projectId: 'pegasus-e40ad',
    authDomain: 'pegasus-e40ad.firebaseapp.com',
    storageBucket: 'pegasus-e40ad.firebasestorage.app',
  );

}